/*

  !!! DO NOT EDIT THIS FILE / CODE IT WAS GENERATED !!!

  generated @2011-06-23 06:52:55
  on http://foomo.interact.com
  THUS, if you this code is missing operations - just regenerate it.

  Oh and if you do not like this code -> fix the generator ;)


*/

(function( window ) {
	// if you do not like "Foomo.Zugspitze.Services.Scaffold" as a name change,
	// then change the $package parameter for RPC::serveClass()
	window.Foomo = window.Foomo || {};
	window.Foomo.Zugspitze = window.Foomo.Zugspitze || {};
	window.Foomo.Zugspitze.Services = window.Foomo.Zugspitze.Services || {};
	window.Foomo.Zugspitze.Services.Scaffold = {
		server: '',
		endPoint: '/foomo/modules/Foomo.Zugspitze/services/scaffold.php/Foomo.Services.RPC/serve',
		/*
			note to self - this is javascript - there is no typing, thus the
			objects may not make sense or should become a json schema ...

		objects: {
			foomoZugspitzeServicesScaffoldLibrary: {
				//
				// string
				id : 'string',
				//
				// string
				name : 'string',
				//
				// string
				description : 'string'
			},
			foomoZugspitzeServicesScaffoldProject: {
				//
				// string
				id : 'string',
				//
				// string
				name : 'string',
				//
				// string
				description : 'string'
			},
			foomoZugspitzeServicesScaffoldApplication: {
				//
				// string
				id : 'string',
				//
				// string
				name : 'string',
				//
				// string
				description : 'string'
			}
		},
		*/
		operations: {
			/**
			  *
			  *
			  *
			  * @return Foomo\Zugspitze\Services\Scaffold\Library[]
			  */
			getLibraries : function() {
				return new this._getLibraries();
			},
			_getLibraries : function() {
				this.data = {
					endPoint: Foomo.Zugspitze.Services.Scaffold.endPoint,
					arguments: {
					},
					complete: false,
					pending: false,
					result: null,
					exception: null,
					errors: [],
					messages: [],
					ajax: null
				};
				this.execute = function(successCallback) {
					this.successCallback = successCallback;
					var me = this;
					this.data.ajax = $.ajax({
						dataType: 'JSON',
						url: window.Foomo.Zugspitze.Services.Scaffold.server + this.data.endPoint + '/getLibraries',
						success: function(data) {
							me.data.result = data.value;
							me.data.exception = data.exception;
							me.data.messages = data.messages;
							if(me.data.exception) {
								me._handleError();
							} else {
								me.data.success = true;
								me.successCallback(me);
							}
						},
						error: function(data) {
							me._handleError();
						}

					});
					return this;
				};
				this._handleError = function(){
					this.data.success = false;
					if(this.errorCallback) {
						this.errorCallback(this);
					}
				},
				this.error = function(errorCallback) {
					this.errorCallback = errorCallback;
					return this;
				};
				return this;

			},
			/**
			  *
			  *
			  * @param string libraryProjectId
			  *
			  * @return Foomo\Zugspitze\Services\Scaffold\Project[]
			  */
			getProjects : function(libraryProjectId) {
				return new this._getProjects(libraryProjectId);
			},
			_getProjects : function(libraryProjectId) {
				this.data = {
					endPoint: Foomo.Zugspitze.Services.Scaffold.endPoint,
					arguments: {
						libraryProjectId : libraryProjectId
					},
					complete: false,
					pending: false,
					result: null,
					exception: null,
					errors: [],
					messages: [],
					ajax: null
				};
				this.execute = function(successCallback) {
					this.successCallback = successCallback;
					var me = this;
					this.data.ajax = $.ajax({
						dataType: 'JSON',
						url: window.Foomo.Zugspitze.Services.Scaffold.server + this.data.endPoint + '/getProjects' + '/' + escape(this.data.arguments.libraryProjectId),
						success: function(data) {
							me.data.result = data.value;
							me.data.exception = data.exception;
							me.data.messages = data.messages;
							if(me.data.exception) {
								me._handleError();
							} else {
								me.data.success = true;
								me.successCallback(me);
							}
						},
						error: function(data) {
							me._handleError();
						}

					});
					return this;
				};
				this._handleError = function(){
					this.data.success = false;
					if(this.errorCallback) {
						this.errorCallback(this);
					}
				},
				this.error = function(errorCallback) {
					this.errorCallback = errorCallback;
					return this;
				};
				return this;

			},
			/**
			  *
			  *
			  * @param string implementationProjectId
			  *
			  * @return Foomo\Zugspitze\Services\Scaffold\Application[]
			  */
			getApplications : function(implementationProjectId) {
				return new this._getApplications(implementationProjectId);
			},
			_getApplications : function(implementationProjectId) {
				this.data = {
					endPoint: Foomo.Zugspitze.Services.Scaffold.endPoint,
					arguments: {
						implementationProjectId : implementationProjectId
					},
					complete: false,
					pending: false,
					result: null,
					exception: null,
					errors: [],
					messages: [],
					ajax: null
				};
				this.execute = function(successCallback) {
					this.successCallback = successCallback;
					var me = this;
					this.data.ajax = $.ajax({
						dataType: 'JSON',
						url: window.Foomo.Zugspitze.Services.Scaffold.server + this.data.endPoint + '/getApplications' + '/' + escape(this.data.arguments.implementationProjectId),
						success: function(data) {
							me.data.result = data.value;
							me.data.exception = data.exception;
							me.data.messages = data.messages;
							if(me.data.exception) {
								me._handleError();
							} else {
								me.data.success = true;
								me.successCallback(me);
							}
						},
						error: function(data) {
							me._handleError();
						}

					});
					return this;
				};
				this._handleError = function(){
					this.data.success = false;
					if(this.errorCallback) {
						this.errorCallback(this);
					}
				},
				this.error = function(errorCallback) {
					this.errorCallback = errorCallback;
					return this;
				};
				return this;

			}

		}
	};
})(window);